### ISSUE TITLE
Name conflict with WireBox' *.map() 

### ISSUE THREAD

**Issue by michael-zock** [clitnak/coldfunctional#1]
This is definitely a great addition, though I had to uninstall the Railo extension again because it came into conflict with the map() method in WireBox, used in tons of ColdBox applications.

Hope it's just a case of the method being too eagerly attached to objects and something that can be settled in a future version (maybe limiting it to instances of java.util.Collection), but in the meantime it's great just to know that a project like this is actually out there.

**Comment by clitnak** [comment]
I logged an issue against Railo. Thanks for the feedback.
https://issues.jboss.org/browse/RAILO-2761

**Comment by clitnak** [comment]
https://issues.jboss.org/browse/RAILO-2761 was rejected. I just released Coldfunctional  v0.2.0 which has an installation feature that should allow you to rename the map() function provided by this extension to something else so it doesn't have to conflict with wirebox.

Thank you for the feedback. Please let me know if there are any problems.
