### ISSUE TITLE
Allow an optional accumulator argument for `reduce`

### ISSUE THREAD

**Issue by bjohn465** [clitnak/coldfunctional#4]
The `reduce` functions use the first item in the collection (array or structure) as the starting value of the accumulator, so the first time the reducer function is called, it receives the first item in the collection and the second item in the collection.

For simple collections, such as collections made up of only numbers or strings, this behavior is okay. If, however, you want to reduce a collection of structures or arrays, it would be helpful to specify the initial value of the accumulator.

For example, without the ability to specify an accumulator, it would be difficult to `reduce` this array of structures to the sum of all the `value`s:

``` coldfusion
<cfset items = [
  { name: "One", value: 1 },
  { name: "Test", value: 42 },
  { name: "Pew pew pew", value: 100 }
] />
```

If an accumulator could be specified, the `reduce` would look something like this:

``` coldfusion
<cfset sum = items.reduce(
  function( sum, item ) {
    return sum + item;
  },
  0
) />
```

If an accumulator isn't specified, the current behavior of using the first item in the collection is appropriate.

**Comment by clitnak** [comment]
great idea. Normally, I would do this, except that railo has implemented reducing functions in the core.
https://github.com/getrailo/railo/commit/9a7ce3d035fef983a065c7cc95a444195de47376

and guess what? they have an 'initial value' argument. Upgrading to 4.2.006 or later and not installing the coldfunctional reducing functions should do the trick.
